# Generated by Django 2.1.7 on 2019-05-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruser',
            name='c_password',
            field=models.CharField(max_length=256),
        ),
    ]
