# Generated by Django 2.1.7 on 2019-05-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_auto_20190520_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruser',
            name='c_is_vip',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='caruser',
            name='c_phone',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
