# Generated by Django 2.1.7 on 2019-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0004_auto_20190523_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruser',
            name='c_car',
            field=models.IntegerField(null=True),
        ),
    ]
