# Generated by Django 2.1.7 on 2019-05-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=16)),
                ('car_icon', models.CharField(max_length=256)),
                ('car_model', models.CharField(max_length=128)),
                ('car_quote', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'carlist',
            },
        ),
    ]
